---
application:
  name: 'mm'
  project: 'test'
  organization: 'QoveryCommunity'
databases:
  - type: 'POSTGRESQL'
    name: 'mmdb'
    version: '13'
  - type: 'REDIS'
    name: 'mmredis'
    version: '6'
routers:
  - name: 'main-mm'
    routes:
      - application_name: 'mm'
        paths:
          - '/'
